<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: The Meaning of Innovation</title>
	<atom:link href="http://werblog.com/2004/11/the-meaning-of-innovation/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2004/11/the-meaning-of-innovation/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: techjunkie</title>
		<link>http://werblog.com/2004/11/the-meaning-of-innovation/#comment-6</link>
		<dc:creator><![CDATA[techjunkie]]></dc:creator>
		<pubDate>Wed, 20 Sep 2006 18:26:57 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1151#comment-6</guid>
		<description><![CDATA[creating new and things to meet needs and wants]]></description>
		<content:encoded><![CDATA[<p>creating new and things to meet needs and wants</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.422 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-02 22:18:12 -->
