<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: The New, New Werblog</title>
	<atom:link href="http://werblog.com/2004/11/the-new-new-werblog/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2004/11/the-new-new-werblog/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: Kevin Werbach</title>
		<link>http://werblog.com/2004/11/the-new-new-werblog/#comment-5</link>
		<dc:creator><![CDATA[Kevin Werbach]]></dc:creator>
		<pubDate>Fri, 05 Nov 2004 18:02:10 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1137#comment-5</guid>
		<description><![CDATA[Testing the comments feature.]]></description>
		<content:encoded><![CDATA[<p>Testing the comments feature.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.394 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-02 19:36:32 -->
