<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: TipTop Tac Toe?</title>
	<atom:link href="http://werblog.com/2004/11/tiptop-tac-toe/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2004/11/tiptop-tac-toe/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: eq2 gold fan</title>
		<link>http://werblog.com/2004/11/tiptop-tac-toe/#comment-8</link>
		<dc:creator><![CDATA[eq2 gold fan]]></dc:creator>
		<pubDate>Wed, 25 Jan 2006 22:10:18 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1155#comment-8</guid>
		<description><![CDATA[&lt;a href=&quot;http://www.washingtonpost.com/wp-dyn/content/article/2006/01/21/AR2006012100094.html&quot; rel=&quot;nofollow&quot;&gt;http://www.washingtonpost.com/wp-dyn/content/article/2006/01/21/AR2006012100094.html&lt;/a&gt;

Look at this article. It explains what&#039;s going on in this area atm. Telecom mamomths just want to get new sources for increasing their income. Actually, they want to bite some piece of cake which don&#039;t belong to them anyhow. It can have disastrous effect on IT ventures.]]></description>
		<content:encoded><![CDATA[<p><a href="http://www.washingtonpost.com/wp-dyn/content/article/2006/01/21/AR2006012100094.html" rel="nofollow">http://www.washingtonpost.com/wp-dyn/content/article/2006/01/21/AR2006012100094.html</a></p>
<p>Look at this article. It explains what&#8217;s going on in this area atm. Telecom mamomths just want to get new sources for increasing their income. Actually, they want to bite some piece of cake which don&#8217;t belong to them anyhow. It can have disastrous effect on IT ventures.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.491 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-05 01:26:59 -->
