<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: The Tivo Fast-Forward Non-Story</title>
	<atom:link href="http://werblog.com/2004/11/the-tivo-fast-forward-non-story/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2004/11/the-tivo-fast-forward-non-story/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: Patrick Ross</title>
		<link>http://werblog.com/2004/11/the-tivo-fast-forward-non-story/#comment-7</link>
		<dc:creator><![CDATA[Patrick Ross]]></dc:creator>
		<pubDate>Wed, 17 Nov 2004 19:26:47 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1153#comment-7</guid>
		<description><![CDATA[I love my TiVo, in fact I was an early adopter of the technology.  You&#039;re right, I don&#039;t have a right to be ad-free, but I&#039;m also under no obligation to pay any attention to the ads.  I plan to keep hearing that bleep-bleep-bleep as I scan through the TV ads, and ignore the banners.  There are bigger issues in the world to lose sleep over.]]></description>
		<content:encoded><![CDATA[<p>I love my TiVo, in fact I was an early adopter of the technology.  You&#8217;re right, I don&#8217;t have a right to be ad-free, but I&#8217;m also under no obligation to pay any attention to the ads.  I plan to keep hearing that bleep-bleep-bleep as I scan through the TV ads, and ignore the banners.  There are bigger issues in the world to lose sleep over.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.409 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-05 00:34:13 -->
