<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Name game</title>
	<atom:link href="http://werblog.com/2006/12/name-game/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2006/12/name-game/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.8</generator>
	<item>
		<title>By: Alexys</title>
		<link>http://werblog.com/2006/12/name-game/#comment-97</link>
		<dc:creator><![CDATA[Alexys]]></dc:creator>
		<pubDate>Sun, 24 Dec 2006 07:41:57 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1398#comment-97</guid>
		<description><![CDATA[veri good idea]]></description>
		<content:encoded><![CDATA[<p>veri good idea</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.474 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-03-10 02:18:37 -->
