<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Implications of Traffic Shaping</title>
	<atom:link href="http://werblog.com/2006/12/implications-of-traffic-shaping/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2006/12/implications-of-traffic-shaping/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: Kevin Werbach</title>
		<link>http://werblog.com/2006/12/implications-of-traffic-shaping/#comment-96</link>
		<dc:creator><![CDATA[Kevin Werbach]]></dc:creator>
		<pubDate>Fri, 22 Dec 2006 16:05:23 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1396#comment-96</guid>
		<description><![CDATA[Metaphorical, FTP is an application.  So is BitTorrent.  And while FTP is a generic way to transfer files, BitTorrent is predominantly used to transfer large objects, especially video.  The ISPs listed aren&#039;t just throttling bandwidth generally; they are shaping BitTorrent specifically.]]></description>
		<content:encoded><![CDATA[<p>Metaphorical, FTP is an application.  So is BitTorrent.  And while FTP is a generic way to transfer files, BitTorrent is predominantly used to transfer large objects, especially video.  The ISPs listed aren&#8217;t just throttling bandwidth generally; they are shaping BitTorrent specifically.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: metaphorical</title>
		<link>http://werblog.com/2006/12/implications-of-traffic-shaping/#comment-95</link>
		<dc:creator><![CDATA[metaphorical]]></dc:creator>
		<pubDate>Fri, 22 Dec 2006 11:38:45 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1396#comment-95</guid>
		<description><![CDATA[BitTorrent seems more like infrastructure than shaping a specific application or provider. BitTorrent is the ftp of multimedia.]]></description>
		<content:encoded><![CDATA[<p>BitTorrent seems more like infrastructure than shaping a specific application or provider. BitTorrent is the ftp of multimedia.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.411 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-07 11:32:40 -->
