<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Experiencing conferences virtually</title>
	<atom:link href="http://werblog.com/2006/03/experiencing-conferences-virtually/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2006/03/experiencing-conferences-virtually/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: PaulSweeney</title>
		<link>http://werblog.com/2006/03/experiencing-conferences-virtually/#comment-77</link>
		<dc:creator><![CDATA[PaulSweeney]]></dc:creator>
		<pubDate>Mon, 13 Mar 2006 14:25:00 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1317#comment-77</guid>
		<description><![CDATA[Hi There,

Quick note re conference organising. We have had loads of interest from conference organisers around our &quot;Interactive Notification&quot; service. Basically, you remind people with voice messages about the conference, maybe you record a message from a key note speaker etc, and then you send it. You might use it to get people to sign up early, or re-confirm, or book their hotel early etc, because at the end of the message they can press 1 to be connected to the hotel etc. etc. The neat thing, is that you can all this from your own desktop right now. I&#039;m afraid we are still in beta at &lt;a href=&quot;http://test.voicesage.com&quot; rel=&quot;nofollow&quot;&gt;http://test.voicesage.com&lt;/a&gt; but if you would like a look just drop me an email and I&#039;ll get you an invite.

Whew. That comment was a lot longer than I planned!

Kind Regards
Paul Sweeney
paul.sweeney@voicesage.com]]></description>
		<content:encoded><![CDATA[<p>Hi There,</p>
<p>Quick note re conference organising. We have had loads of interest from conference organisers around our &#8220;Interactive Notification&#8221; service. Basically, you remind people with voice messages about the conference, maybe you record a message from a key note speaker etc, and then you send it. You might use it to get people to sign up early, or re-confirm, or book their hotel early etc, because at the end of the message they can press 1 to be connected to the hotel etc. etc. The neat thing, is that you can all this from your own desktop right now. I&#8217;m afraid we are still in beta at <a href="http://test.voicesage.com" rel="nofollow">http://test.voicesage.com</a> but if you would like a look just drop me an email and I&#8217;ll get you an invite.</p>
<p>Whew. That comment was a lot longer than I planned!</p>
<p>Kind Regards<br />
Paul Sweeney<br />
<a href="mailto:paul.sweeney@voicesage.com">paul.sweeney@voicesage.com</a></p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.398 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-04 22:01:10 -->
