<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: The future of Eudora</title>
	<atom:link href="http://werblog.com/2006/10/the-future-of-eudora/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2006/10/the-future-of-eudora/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: Gen</title>
		<link>http://werblog.com/2006/10/the-future-of-eudora/#comment-92</link>
		<dc:creator><![CDATA[Gen]]></dc:creator>
		<pubDate>Sat, 14 Oct 2006 02:02:44 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1390#comment-92</guid>
		<description><![CDATA[Kevin, the wonderful thing about this new future for Eudora is that, because Mozilla is open source, everyone, including you, can have a say in what happens.  If you are active in the community, make a strong case for your needs/wants/desires for the future Eudora/Thunderbird platform, the developers will take your requests seriously.

What I mean to say is that the future for Eudora is what you (and other people who still use/care about Eudora) make of it.  Literally.

I urge you to stay in touch with the &quot;penelope&quot; project&#039;s status with the project wiki:

&lt;a href=&quot;http://wiki.mozilla.org/Penelope&quot; rel=&quot;nofollow&quot;&gt;http://wiki.mozilla.org/Penelope&lt;/a&gt;

(disclaimer: I work for Mozilla)]]></description>
		<content:encoded><![CDATA[<p>Kevin, the wonderful thing about this new future for Eudora is that, because Mozilla is open source, everyone, including you, can have a say in what happens.  If you are active in the community, make a strong case for your needs/wants/desires for the future Eudora/Thunderbird platform, the developers will take your requests seriously.</p>
<p>What I mean to say is that the future for Eudora is what you (and other people who still use/care about Eudora) make of it.  Literally.</p>
<p>I urge you to stay in touch with the &#8220;penelope&#8221; project&#8217;s status with the project wiki:</p>
<p><a href="http://wiki.mozilla.org/Penelope" rel="nofollow">http://wiki.mozilla.org/Penelope</a></p>
<p>(disclaimer: I work for Mozilla)</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.486 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-07 08:45:10 -->
