<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Life as a working parent</title>
	<atom:link href="http://werblog.com/2006/04/life-as-a-working-parent/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2006/04/life-as-a-working-parent/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: TheOnlineLawyer</title>
		<link>http://werblog.com/2006/04/life-as-a-working-parent/#comment-86</link>
		<dc:creator><![CDATA[TheOnlineLawyer]]></dc:creator>
		<pubDate>Wed, 24 May 2006 19:04:12 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1358#comment-86</guid>
		<description><![CDATA[Several years ago my wife wanted me to coach our oldest son&#039;s flag football team.  I was working in a lawyer mill (6:30A-8:30P plus weekends) at the time preparing for trial in a $4 mil case.  I really didn&#039;t have any extra time to spend on the kids.  Then she sent me this article titled &quot;Going &#039;Quality of Life.&#039;&quot;  It was about an attorney who just bailed out of the fast lane one day and landed in a job that actually allowed him time to stop and think.  A year later I decided to do the same thing and have praised the decision ever since.  I was luck though.  Not all working parents can find a job that allow for &quot;Quality of Life.&quot;]]></description>
		<content:encoded><![CDATA[<p>Several years ago my wife wanted me to coach our oldest son&#8217;s flag football team.  I was working in a lawyer mill (6:30A-8:30P plus weekends) at the time preparing for trial in a $4 mil case.  I really didn&#8217;t have any extra time to spend on the kids.  Then she sent me this article titled &#8220;Going &#8216;Quality of Life.'&#8221;  It was about an attorney who just bailed out of the fast lane one day and landed in a job that actually allowed him time to stop and think.  A year later I decided to do the same thing and have praised the decision ever since.  I was luck though.  Not all working parents can find a job that allow for &#8220;Quality of Life.&#8221;</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.411 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-04 23:02:47 -->
