<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Syndication in action</title>
	<atom:link href="http://werblog.com/2006/02/syndication-in-action/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2006/02/syndication-in-action/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
	<item>
		<title>By: Charlie Wood</title>
		<link>http://werblog.com/2006/02/syndication-in-action/#comment-76</link>
		<dc:creator><![CDATA[Charlie Wood]]></dc:creator>
		<pubDate>Thu, 23 Feb 2006 12:53:01 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1307#comment-76</guid>
		<description><![CDATA[Similarly, 40% of all of Salesforce.com&#039;s traffic comes through their web services API.

&lt;a href=&quot;http://blog.sforce.com/sforce/2006/01/hello_appexchan.html&quot; rel=&quot;nofollow&quot;&gt;&lt;a href=&quot;http://blog.sforce.com/sforce/2006/01/hello_appexchan.html&quot; rel=&quot;nofollow&quot;&gt;http://blog.sforce.com/sforce/2006/01/hello_appexchan.html&lt;/a&gt;&lt;/a&gt;]]></description>
		<content:encoded><![CDATA[<p>Similarly, 40% of all of Salesforce.com&#8217;s traffic comes through their web services API.</p>
<p><a href="http://blog.sforce.com/sforce/2006/01/hello_appexchan.html" rel="nofollow"></a><a href="http://blog.sforce.com/sforce/2006/01/hello_appexchan.html" rel="nofollow">http://blog.sforce.com/sforce/2006/01/hello_appexchan.html</a></p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.437 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-24 20:08:16 -->
