<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Teaching as Learning</title>
	<atom:link href="http://werblog.com/2013/10/teaching-as-learning/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2013/10/teaching-as-learning/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
	<item>
		<title>By: Ugg Boots Aus Amerika Bestellen</title>
		<link>http://werblog.com/2013/10/teaching-as-learning/#comment-1726</link>
		<dc:creator><![CDATA[Ugg Boots Aus Amerika Bestellen]]></dc:creator>
		<pubDate>Wed, 27 Nov 2013 18:35:26 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/?p=4367#comment-1726</guid>
		<description><![CDATA[&#124;When I want to place gallery or LightBox or yet a slider on my site I always attempt to use jQuery script for that.]]></description>
		<content:encoded><![CDATA[<p>|When I want to place gallery or LightBox or yet a slider on my site I always attempt to use jQuery script for that.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Billige Ugg Boots</title>
		<link>http://werblog.com/2013/10/teaching-as-learning/#comment-1722</link>
		<dc:creator><![CDATA[Billige Ugg Boots]]></dc:creator>
		<pubDate>Mon, 25 Nov 2013 06:33:59 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/?p=4367#comment-1722</guid>
		<description><![CDATA[Yup, you are correct Google is the most excellent in favor of blogging, Google]]></description>
		<content:encoded><![CDATA[<p>Yup, you are correct Google is the most excellent in favor of blogging, Google</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Anonymous</title>
		<link>http://werblog.com/2013/10/teaching-as-learning/#comment-1644</link>
		<dc:creator><![CDATA[Anonymous]]></dc:creator>
		<pubDate>Mon, 28 Oct 2013 12:10:58 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/?p=4367#comment-1644</guid>
		<description><![CDATA[&quot;At the same time, it is only when failure doesn’t seem scary that we are willing to experiment.  That is one reason games are such exceptional learning tools.  They invite us to try and fail, and fail, and fail, until we eventually succeed. You can always start over with another life or a new session of the game.&quot;  The amount of wisdom contained in this thought is profound. While a perfect and welcome fit for the students, the challenge is convincing our teaching colleagues of its importance...]]></description>
		<content:encoded><![CDATA[<p>&#8220;At the same time, it is only when failure doesn’t seem scary that we are willing to experiment.  That is one reason games are such exceptional learning tools.  They invite us to try and fail, and fail, and fail, until we eventually succeed. You can always start over with another life or a new session of the game.&#8221;  The amount of wisdom contained in this thought is profound. While a perfect and welcome fit for the students, the challenge is convincing our teaching colleagues of its importance&#8230;</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.477 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-29 14:54:35 -->
