<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Euro telcos challenge the Internet model. I&#8217;ve alw&#8230;</title>
	<atom:link href="http://werblog.com/tweets/63236246448766976/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/tweets/63236246448766976/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Thu, 03 Sep 2015 11:13:25 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4</generator>
</channel>
</rss>

<!-- Dynamic page generated in 0.374 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-01-01 18:14:06 -->
