<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	>

<channel>
	<title>Judaism &#8211; Werblog</title>
	<atom:link href="http://werblog.com/category/judaism/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Fri, 19 Aug 2016 21:51:08 +0000</lastBuildDate>
	<language>en-US</language>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
	<item>
		<title>Our Jewish Christmas Eve</title>
		<link>http://werblog.com/2012/12/christmas-eve/</link>
		<pubDate>Mon, 24 Dec 2012 15:25:16 +0000</pubDate>
		<dc:creator><![CDATA[kwerb]]></dc:creator>
				<category><![CDATA[Judaism]]></category>
		<category><![CDATA[Uncategorized]]></category>

		<guid isPermaLink="false">http://werblog.com/?p=2587</guid>
		<description><![CDATA[We have a tradition in my family of using Christmas Eve as an excuse for a hearty home-cooked family dinner, usually followed by making a fire in the fireplace and enjoying games or a movie together. Normally it&#8217;s my super-dense split pea soup, but this year I made that for Chanukah.  I made so much, ...<a class="post-readmore" href="http://werblog.com/2012/12/christmas-eve/">read more</a>]]></description>
				<content:encoded><![CDATA[<p>We have a tradition in my family of using Christmas Eve as an excuse for a hearty home-cooked family dinner, usually followed by making a fire in the fireplace and enjoying games or a movie together. Normally it&#8217;s my super-dense split pea soup, but this year I made that for Chanukah.  I made so much, in fact, that we were eating it for a week afterwards.  Time for something different.  So tonight, I&#8217;ll be doing stuffed cabbage (veggie for me, ground turkey for everyone else), and then we&#8217;ll move on to s&#8217;mores and Austin Powers.</p>
<p>We&#8217;re not Christian, of course. Yet it feels somehow right to borrow what we appreciate from the cultural environment we live in.  As my <a href="http://mikeknopf.wordpress.com/about-rabbi-knopf/">Rabbi</a> points out, Jews have done that for thousands of years &#8212; the tzitzit or fringes on our prayer shawls were appropriated from Egyptian royalty.  The key, I think, is to borrow in a way that celebrates the best of both traditions. For most Americans, Christmas seems to be less about Jesus than shopping, but we can all agree on this as a time for family togetherness, as the year draws to a close.</p>
<p>Now we&#8217;ll see how the stuffed cabbage comes out&#8230;.</p>
]]></content:encoded>
			</item>
	</channel>
</rss>

<!-- Dynamic page generated in 1.157 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-26 21:47:51 -->
