<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	>

<channel>
	<title>stuff &#8211; Werblog</title>
	<atom:link href="http://werblog.com/category/stuff/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Fri, 19 Aug 2016 21:51:08 +0000</lastBuildDate>
	<language>en-US</language>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
	<item>
		<title>Under Construction</title>
		<link>http://werblog.com/2013/02/under-construction-3/</link>
		<pubDate>Sun, 10 Feb 2013 19:23:44 +0000</pubDate>
		<dc:creator><![CDATA[kwerb]]></dc:creator>
				<category><![CDATA[stuff]]></category>
		<category><![CDATA[Uncategorized]]></category>

		<guid isPermaLink="false">http://werblog.com/?p=4156</guid>
		<description><![CDATA[I finally decided to update my ancient blog template and make some other changes behind the scenes.  Hopefully this will give me some motivation to start posting here again.  Please pardon the mess while I work on things. Thanks!]]></description>
				<content:encoded><![CDATA[<p>I finally decided to update my ancient blog template and make some other changes behind the scenes.  Hopefully this will give me some motivation to start posting here again.  Please pardon the mess while I work on things. Thanks!</p>
]]></content:encoded>
			</item>
	</channel>
</rss>

<!-- Dynamic page generated in 1.041 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-28 18:01:47 -->
