<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: A new Y2K bug?</title>
	<atom:link href="http://werblog.com/2007/01/a-new-y2k-bug/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2007/01/a-new-y2k-bug/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.9</generator>
	<item>
		<title>By: albert sun</title>
		<link>http://werblog.com/2007/01/a-new-y2k-bug/#comment-98</link>
		<dc:creator><![CDATA[albert sun]]></dc:creator>
		<pubDate>Tue, 30 Jan 2007 04:07:20 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1415#comment-98</guid>
		<description><![CDATA[That&#039;s a really interesting development. I&#039;m the technology reporter for the Daily Pennsylvanian, I&#039;d like to hear more about this issue. Possibly around March 11th, we can run a story about this.]]></description>
		<content:encoded><![CDATA[<p>That&#8217;s a really interesting development. I&#8217;m the technology reporter for the Daily Pennsylvanian, I&#8217;d like to hear more about this issue. Possibly around March 11th, we can run a story about this.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.933 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-05-07 21:15:18 -->
