<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Not my last FM</title>
	<atom:link href="http://werblog.com/2007/03/not-my-last-fm/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2007/03/not-my-last-fm/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.10</generator>
	<item>
		<title>By: Ryan Stewart</title>
		<link>http://werblog.com/2007/03/not-my-last-fm/#comment-101</link>
		<dc:creator><![CDATA[Ryan Stewart]]></dc:creator>
		<pubDate>Fri, 02 Mar 2007 19:28:55 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1424#comment-101</guid>
		<description><![CDATA[You should check out Finetune - &lt;a href=&quot;http://www.finetune.com/&quot; rel=&quot;nofollow&quot;&gt;http://www.finetune.com/&lt;/a&gt; - it&#039;s a slick service. Kind of a blend between Last.fm and Pandora.]]></description>
		<content:encoded><![CDATA[<p>You should check out Finetune &#8211; <a href="http://www.finetune.com/" rel="nofollow">http://www.finetune.com/</a> &#8211; it&#8217;s a slick service. Kind of a blend between Last.fm and Pandora.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.453 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-06-06 16:48:25 -->
