<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: SpamSoap Update #1</title>
	<atom:link href="http://werblog.com/2007/01/spamsoap-update-1-2/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2007/01/spamsoap-update-1-2/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.9</generator>
	<item>
		<title>By: Gen</title>
		<link>http://werblog.com/2007/01/spamsoap-update-1-2/#comment-99</link>
		<dc:creator><![CDATA[Gen]]></dc:creator>
		<pubDate>Thu, 01 Feb 2007 03:31:09 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1417#comment-99</guid>
		<description><![CDATA[Kevin, thank you, thank you, thank you for this update!  I&#039;m on the fence in consideration of an outsourced anti-spam solution and I think you&#039;ve pushed me over the edge.]]></description>
		<content:encoded><![CDATA[<p>Kevin, thank you, thank you, thank you for this update!  I&#8217;m on the fence in consideration of an outsourced anti-spam solution and I think you&#8217;ve pushed me over the edge.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.393 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-05-08 19:07:44 -->
