<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	>

<channel>
	<title>Search Results for &#8220;gmification&#8221; &#8211; Werblog</title>
	<atom:link href="http://werblog.com/search/gmification/feed/rss2/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Thu, 01 Dec 2016 20:45:25 +0000</lastBuildDate>
	<language>en-US</language>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.8</generator>
</channel>
</rss>

<!-- Dynamic page generated in 0.552 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-03-15 08:58:16 -->
