<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: About</title>
	<atom:link href="http://werblog.com/about-2/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
	<item>
		<title>By: Direktori Wisata</title>
		<link>http://werblog.com/about-2/#comment-30663</link>
		<dc:creator><![CDATA[Direktori Wisata]]></dc:creator>
		<pubDate>Sun, 14 Feb 2016 11:16:03 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?page_id=1512#comment-30663</guid>
		<description><![CDATA[Thank you for sharing useful knowledge and information. Greeting from Indonesia]]></description>
		<content:encoded><![CDATA[<p>Thank you for sharing useful knowledge and information. Greeting from Indonesia</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Jean-Paul Bourque</title>
		<link>http://werblog.com/about-2/#comment-29434</link>
		<dc:creator><![CDATA[Jean-Paul Bourque]]></dc:creator>
		<pubDate>Thu, 03 Sep 2015 11:13:25 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?page_id=1512#comment-29434</guid>
		<description><![CDATA[I would be humanly enriched to receive the notifications indicated below. Thank you.  Jean-Paul]]></description>
		<content:encoded><![CDATA[<p>I would be humanly enriched to receive the notifications indicated below. Thank you.  Jean-Paul</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: abigail nasser</title>
		<link>http://werblog.com/about-2/#comment-29169</link>
		<dc:creator><![CDATA[abigail nasser]]></dc:creator>
		<pubDate>Thu, 13 Aug 2015 10:52:23 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?page_id=1512#comment-29169</guid>
		<description><![CDATA[Hello,
 
I’d like to inquire if it’s possible to purchase advertising space on werblog.com.
If there is any space available please let me know and we could discuss further details.
Looking forward to your positive reply.
 
Thanks,
 
Abigail]]></description>
		<content:encoded><![CDATA[<p>Hello,</p>
<p>I’d like to inquire if it’s possible to purchase advertising space on werblog.com.<br />
If there is any space available please let me know and we could discuss further details.<br />
Looking forward to your positive reply.</p>
<p>Thanks,</p>
<p>Abigail</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.466 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-24 09:54:57 -->
