<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: I Want My Mobile TV</title>
	<atom:link href="http://werblog.com/2005/10/i-want-my-mobile-tv/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/10/i-want-my-mobile-tv/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: T-Bond</title>
		<link>http://werblog.com/2005/10/i-want-my-mobile-tv/#comment-70</link>
		<dc:creator><![CDATA[T-Bond]]></dc:creator>
		<pubDate>Thu, 13 Oct 2005 20:33:09 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1279#comment-70</guid>
		<description><![CDATA[Immediately before reading your post, I wrote that my thinking has changed a little in regard to the value of content.  I asked, &quot;will millions of people pay $1.99 to watch last nights prime show&quot;?  I actually purchased share in TWX because advertising revenues are zooming now that the portal is open.  It seems that a mashup with Google could monetize magazines and videos.

I have assumed that one would subscribe to CBS for may $4.95 per month.  I figured a college football package from ESPN might run $6.95 per month.  I may have been underestimating.  My brother, an old foggie who watches baseball and not a lot more, says he would pay extra to watch what and when.  You are right, producers may be in for a windfall!]]></description>
		<content:encoded><![CDATA[<p>Immediately before reading your post, I wrote that my thinking has changed a little in regard to the value of content.  I asked, &#8220;will millions of people pay $1.99 to watch last nights prime show&#8221;?  I actually purchased share in TWX because advertising revenues are zooming now that the portal is open.  It seems that a mashup with Google could monetize magazines and videos.</p>
<p>I have assumed that one would subscribe to CBS for may $4.95 per month.  I figured a college football package from ESPN might run $6.95 per month.  I may have been underestimating.  My brother, an old foggie who watches baseball and not a lot more, says he would pay extra to watch what and when.  You are right, producers may be in for a windfall!</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.385 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-04 22:37:55 -->
