<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Sicky Wicky</title>
	<atom:link href="http://werblog.com/2005/03/sicky-wicky/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/03/sicky-wicky/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: Kevin Werbach</title>
		<link>http://werblog.com/2005/03/sicky-wicky/#comment-20</link>
		<dc:creator><![CDATA[Kevin Werbach]]></dc:creator>
		<pubDate>Wed, 30 Mar 2005 02:52:45 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1216#comment-20</guid>
		<description><![CDATA[Turns out I have a sinus infection and conjunctivitis (Pink Eye).  Not fun.  At least now I&#039;m on antibiotics and other prescription medication, so hopefully I&#039;ll start feeling better.

Keeping my fingers crossed I don&#039;t give it to anyone else in the family.]]></description>
		<content:encoded><![CDATA[<p>Turns out I have a sinus infection and conjunctivitis (Pink Eye).  Not fun.  At least now I&#8217;m on antibiotics and other prescription medication, so hopefully I&#8217;ll start feeling better.</p>
<p>Keeping my fingers crossed I don&#8217;t give it to anyone else in the family.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Kevin Werbach</title>
		<link>http://werblog.com/2005/03/sicky-wicky/#comment-19</link>
		<dc:creator><![CDATA[Kevin Werbach]]></dc:creator>
		<pubDate>Wed, 30 Mar 2005 02:51:44 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1216#comment-19</guid>
		<description><![CDATA[Turns out I have a sinus infection and conjunctivitis (Pink Eye).  Not fun.  At least now I&#039;m on antibiotics and other prescription medication, so hopefully I&#039;ll start feeling better.

Keeping my fingers crossed I don&#039;t give it to anyone else in the family.]]></description>
		<content:encoded><![CDATA[<p>Turns out I have a sinus infection and conjunctivitis (Pink Eye).  Not fun.  At least now I&#8217;m on antibiotics and other prescription medication, so hopefully I&#8217;ll start feeling better.</p>
<p>Keeping my fingers crossed I don&#8217;t give it to anyone else in the family.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Chris Lehmann</title>
		<link>http://werblog.com/2005/03/sicky-wicky/#comment-18</link>
		<dc:creator><![CDATA[Chris Lehmann]]></dc:creator>
		<pubDate>Wed, 30 Mar 2005 00:58:10 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1216#comment-18</guid>
		<description><![CDATA[Well, I just spent the last 25 minutes rocking a very sick Jakob to sleep... Kat is sick and I&#039;m fighting it.

So I can relate.]]></description>
		<content:encoded><![CDATA[<p>Well, I just spent the last 25 minutes rocking a very sick Jakob to sleep&#8230; Kat is sick and I&#8217;m fighting it.</p>
<p>So I can relate.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: smurfette</title>
		<link>http://werblog.com/2005/03/sicky-wicky/#comment-17</link>
		<dc:creator><![CDATA[smurfette]]></dc:creator>
		<pubDate>Tue, 29 Mar 2005 04:06:16 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1216#comment-17</guid>
		<description><![CDATA[&quot;rainy days and mondays always get me down&quot;, not to mention some rainy monday.
best wishes for your family and good luck with your coming speech!]]></description>
		<content:encoded><![CDATA[<p>&#8220;rainy days and mondays always get me down&#8221;, not to mention some rainy monday.<br />
best wishes for your family and good luck with your coming speech!</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.420 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-02 21:09:21 -->
