<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: What a party</title>
	<atom:link href="http://werblog.com/2005/05/what-a-party/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/05/what-a-party/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: Music Code</title>
		<link>http://werblog.com/2005/05/what-a-party/#comment-23</link>
		<dc:creator><![CDATA[Music Code]]></dc:creator>
		<pubDate>Wed, 03 May 2006 12:54:09 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1231#comment-23</guid>
		<description><![CDATA[nice =)]]></description>
		<content:encoded><![CDATA[<p>nice =)</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.393 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-02 22:03:39 -->
