<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Here Comes the Videonet</title>
	<atom:link href="http://werblog.com/2005/09/here-comes-the-videonet/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/09/here-comes-the-videonet/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.10</generator>
	<item>
		<title>By: T-Bond</title>
		<link>http://werblog.com/2005/09/here-comes-the-videonet/#comment-65</link>
		<dc:creator><![CDATA[T-Bond]]></dc:creator>
		<pubDate>Sun, 25 Sep 2005 04:14:58 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1252#comment-65</guid>
		<description><![CDATA[Amen brother!  The video distribution tails will grow very long when the majority of high school football games (from the viewpoint of numerous parents) and millions of other videos are stored on the internet. Advertising revenues from forgotten shows of the past will produce &quot;found money&quot; for those who allow scanning and distribution.  It took many years for total cable viewing to surpase total network viewing.  The adoption of &quot;free&quot; IP-Video viewing will happen much more rapidly.]]></description>
		<content:encoded><![CDATA[<p>Amen brother!  The video distribution tails will grow very long when the majority of high school football games (from the viewpoint of numerous parents) and millions of other videos are stored on the internet. Advertising revenues from forgotten shows of the past will produce &#8220;found money&#8221; for those who allow scanning and distribution.  It took many years for total cable viewing to surpase total network viewing.  The adoption of &#8220;free&#8221; IP-Video viewing will happen much more rapidly.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.421 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-06-06 17:04:31 -->
