<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: The FCC stands up for VOIP</title>
	<atom:link href="http://werblog.com/2005/03/the-fcc-stands-up-for-voip/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/03/the-fcc-stands-up-for-voip/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.5</generator>
	<item>
		<title>By: Aswath</title>
		<link>http://werblog.com/2005/03/the-fcc-stands-up-for-voip/#comment-16</link>
		<dc:creator><![CDATA[Aswath]]></dc:creator>
		<pubDate>Fri, 04 Mar 2005 14:24:02 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1205#comment-16</guid>
		<description><![CDATA[Evidently, Vonage was seeking more than &quot;guidence&quot; (see the comment on your Feb. 17th entry) and FCC was conducting a formal investigation on this matter . :-)

On another matter, can you tell us whether &quot;section 201(b) of the Communications Act of 1934, as amended&quot; is applicable to Cable access providers? In other words, are cable providers bound by the precedence of this consent decree.]]></description>
		<content:encoded><![CDATA[<p>Evidently, Vonage was seeking more than &#8220;guidence&#8221; (see the comment on your Feb. 17th entry) and FCC was conducting a formal investigation on this matter . <img src="http://werbach.com/wordpress/wp-includes/images/smilies/simple-smile.png" alt=":-)" class="wp-smiley" style="height: 1em; max-height: 1em;" /></p>
<p>On another matter, can you tell us whether &#8220;section 201(b) of the Communications Act of 1934, as amended&#8221; is applicable to Cable access providers? In other words, are cable providers bound by the precedence of this consent decree.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.536 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-09-29 06:07:55 -->
