<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Two kinds of Internet video</title>
	<atom:link href="http://werblog.com/2005/10/two-kinds-of-internet-video/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/10/two-kinds-of-internet-video/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: absinth42</title>
		<link>http://werblog.com/2005/10/two-kinds-of-internet-video/#comment-69</link>
		<dc:creator><![CDATA[absinth42]]></dc:creator>
		<pubDate>Tue, 01 Nov 2005 11:15:23 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1274#comment-69</guid>
		<description><![CDATA[This is a &quot;message in a bottle&quot;.
I am sixty-one years of age.
I have never corresponded on line.
Retired USG service.
Presentable.
HEY!,a body&#039;s gotta laugh, right?
If there&#039;s a woman out there (40-60) who is posessed by an improbable sense of humor, contact pdmh028@webtv.net-mere prescient observation,not bitter cynicism warms my
heart.
                       pdmh028@webtv.net
                          Paul]]></description>
		<content:encoded><![CDATA[<p>This is a &#8220;message in a bottle&#8221;.<br />
I am sixty-one years of age.<br />
I have never corresponded on line.<br />
Retired USG service.<br />
Presentable.<br />
HEY!,a body&#8217;s gotta laugh, right?<br />
If there&#8217;s a woman out there (40-60) who is posessed by an improbable sense of humor, contact <a href="mailto:pdmh028@webtv.net">pdmh028@webtv.net</a>-mere prescient observation,not bitter cynicism warms my<br />
heart.<br />
                       <a href="mailto:pdmh028@webtv.net">pdmh028@webtv.net</a><br />
                          Paul</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: absinth42</title>
		<link>http://werblog.com/2005/10/two-kinds-of-internet-video/#comment-68</link>
		<dc:creator><![CDATA[absinth42]]></dc:creator>
		<pubDate>Tue, 01 Nov 2005 11:13:10 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1274#comment-68</guid>
		<description><![CDATA[This is a &quot;message in a bottle&quot;.
I am sixty-one years of age.
I have never corresponded on line.
Retired USG service.
Presentable.
HEY!,a body&#039;s gotta laugh, right?
If there&#039;s a woman out there (40-60) who is posessed by an improbable sense of humor, contact pdmh028@webtv.net-mere prescient observation,not bitter cynicism warms my
heart.
                       pdmh028@webtv.net
                          Paul]]></description>
		<content:encoded><![CDATA[<p>This is a &#8220;message in a bottle&#8221;.<br />
I am sixty-one years of age.<br />
I have never corresponded on line.<br />
Retired USG service.<br />
Presentable.<br />
HEY!,a body&#8217;s gotta laugh, right?<br />
If there&#8217;s a woman out there (40-60) who is posessed by an improbable sense of humor, contact <a href="mailto:pdmh028@webtv.net">pdmh028@webtv.net</a>-mere prescient observation,not bitter cynicism warms my<br />
heart.<br />
                       <a href="mailto:pdmh028@webtv.net">pdmh028@webtv.net</a><br />
                          Paul</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.401 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-05 01:51:13 -->
