<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: VOIP confusion</title>
	<atom:link href="http://werblog.com/2005/09/voip-confusion/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/09/voip-confusion/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.10</generator>
	<item>
		<title>By: Rob Frieden</title>
		<link>http://werblog.com/2005/09/voip-confusion/#comment-66</link>
		<dc:creator><![CDATA[Rob Frieden]]></dc:creator>
		<pubDate>Fri, 30 Sep 2005 20:49:57 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1256#comment-66</guid>
		<description><![CDATA[Hello All:

   Kevin&#039;s quite right about incrementalism at the FCC on VoIP. I believe it will become increasingly difficult for the FCC to work with legislatively crafted service classifications, such as telecommunications, telecommunications service and information service. In reclassifying DSL from telecommunications service to information service the FCC had to find a way to ignore or subsume the telecommunications function that served as the foundation for applying Title II common carrier regulation.
    In the CALEA wiretap order the FCC had to make another pragmatic acknowledgement: that the definition of â€œtelecommunications carrierâ€ in CALEA covers a broader range of ventures than a similar term used in the Communications Act.
So we now have telecommunications, which means bit transport that&#039;s not stand alone and at least two types of telecommunications service providers, depending on whether it&#039;s law enforcement or telecommunications policy at issue.
Confusing.]]></description>
		<content:encoded><![CDATA[<p>Hello All:</p>
<p>   Kevin&#8217;s quite right about incrementalism at the FCC on VoIP. I believe it will become increasingly difficult for the FCC to work with legislatively crafted service classifications, such as telecommunications, telecommunications service and information service. In reclassifying DSL from telecommunications service to information service the FCC had to find a way to ignore or subsume the telecommunications function that served as the foundation for applying Title II common carrier regulation.<br />
    In the CALEA wiretap order the FCC had to make another pragmatic acknowledgement: that the definition of â€œtelecommunications carrierâ€ in CALEA covers a broader range of ventures than a similar term used in the Communications Act.<br />
So we now have telecommunications, which means bit transport that&#8217;s not stand alone and at least two types of telecommunications service providers, depending on whether it&#8217;s law enforcement or telecommunications policy at issue.<br />
Confusing.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.411 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-06-06 17:05:09 -->
