<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Billions and Billions served</title>
	<atom:link href="http://werblog.com/2005/02/billions-and-billions-served/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/02/billions-and-billions-served/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: JonathanAquino</title>
		<link>http://werblog.com/2005/02/billions-and-billions-served/#comment-14</link>
		<dc:creator><![CDATA[JonathanAquino]]></dc:creator>
		<pubDate>Thu, 24 Feb 2005 04:48:00 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1197#comment-14</guid>
		<description><![CDATA[Amazingly, the Internet Archive (home of the Wayback Machine) has offered to host unlimited audio and video content forever (provided that they are licensed under the Creative Commons). This is an awesome undertaking.

You can do this today! Google for the ccPublisher upload program.]]></description>
		<content:encoded><![CDATA[<p>Amazingly, the Internet Archive (home of the Wayback Machine) has offered to host unlimited audio and video content forever (provided that they are licensed under the Creative Commons). This is an awesome undertaking.</p>
<p>You can do this today! Google for the ccPublisher upload program.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.490 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-02 19:35:22 -->
