<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: The End of Operating Systems?</title>
	<atom:link href="http://werblog.com/2006/03/the-end-of-operating-systems/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2006/03/the-end-of-operating-systems/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: Ryan Stewart</title>
		<link>http://werblog.com/2006/03/the-end-of-operating-systems/#comment-79</link>
		<dc:creator><![CDATA[Ryan Stewart]]></dc:creator>
		<pubDate>Thu, 23 Mar 2006 21:48:35 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1333#comment-79</guid>
		<description><![CDATA[I have no idea why I didn&#039;t think of this angle before, but it&#039;s an excellent question.  The slew of Rich Internet Applications, the heavy adoption of AJAX and the advancements in the Flash Platform are slowly eating away at the OS market.  It will be years before web apps win out entirely, but that may be long enough to make Microsoft think twice about another OS.  Great, great post.]]></description>
		<content:encoded><![CDATA[<p>I have no idea why I didn&#8217;t think of this angle before, but it&#8217;s an excellent question.  The slew of Rich Internet Applications, the heavy adoption of AJAX and the advancements in the Flash Platform are slowly eating away at the OS market.  It will be years before web apps win out entirely, but that may be long enough to make Microsoft think twice about another OS.  Great, great post.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.387 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-07 10:16:34 -->
