<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: The Beeb</title>
	<atom:link href="http://werblog.com/2006/04/the-beeb/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2006/04/the-beeb/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: penis enlargement</title>
		<link>http://werblog.com/2006/04/the-beeb/#comment-84</link>
		<dc:creator><![CDATA[penis enlargement]]></dc:creator>
		<pubDate>Tue, 08 Aug 2006 21:58:02 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1345#comment-84</guid>
		<description><![CDATA[Great review, Kevin!]]></description>
		<content:encoded><![CDATA[<p>Great review, Kevin!</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: AJ Carey</title>
		<link>http://werblog.com/2006/04/the-beeb/#comment-83</link>
		<dc:creator><![CDATA[AJ Carey]]></dc:creator>
		<pubDate>Wed, 12 Apr 2006 19:34:38 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1345#comment-83</guid>
		<description><![CDATA[I find telecom policy in other countries particularly fascinating and especially those in England and its former colonies like Canada and New Zealand. Part of what intrigues me is their undying faith in the power of government to &quot;fix&quot; things. I just don&#039;t get it. Almost every example of government regulation in the United States has been a case study in failure. I think that it would be the case for net neutrality as well. The free market is generally a much more successful venue.]]></description>
		<content:encoded><![CDATA[<p>I find telecom policy in other countries particularly fascinating and especially those in England and its former colonies like Canada and New Zealand. Part of what intrigues me is their undying faith in the power of government to &#8220;fix&#8221; things. I just don&#8217;t get it. Almost every example of government regulation in the United States has been a case study in failure. I think that it would be the case for net neutrality as well. The free market is generally a much more successful venue.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.413 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-05 15:55:38 -->
