<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Backwards spectrum policy</title>
	<atom:link href="http://werblog.com/2006/02/backwards-spectrum-policy/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2006/02/backwards-spectrum-policy/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: Enclick</title>
		<link>http://werblog.com/2006/02/backwards-spectrum-policy/#comment-75</link>
		<dc:creator><![CDATA[Enclick]]></dc:creator>
		<pubDate>Sun, 14 May 2006 16:06:55 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1301#comment-75</guid>
		<description><![CDATA[The news is

&quot;Web Radio Overtakes AM/FM radio among evening listeners&quot;

Spectrum  licensees might soon loose the will to pay the administration. As communication costs decrease,  the license becomes a greater part of a broadcast project cost.]]></description>
		<content:encoded><![CDATA[<p>The news is</p>
<p>&#8220;Web Radio Overtakes AM/FM radio among evening listeners&#8221;</p>
<p>Spectrum  licensees might soon loose the will to pay the administration. As communication costs decrease,  the license becomes a greater part of a broadcast project cost.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.399 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-05 17:03:16 -->
