<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: &#034;It stops being the Net&#034;</title>
	<atom:link href="http://werblog.com/2006/03/it-stops-being-the-net/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2006/03/it-stops-being-the-net/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: AJ Carey</title>
		<link>http://werblog.com/2006/03/it-stops-being-the-net/#comment-80</link>
		<dc:creator><![CDATA[AJ Carey]]></dc:creator>
		<pubDate>Tue, 04 Apr 2006 22:13:41 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1339#comment-80</guid>
		<description><![CDATA[Kevin, which plans to violate net neutrality are you talking about, cause I haven&#039;t seen any? As far as I can tell, the telco&#039;s aren&#039;t going to do anything wrong, even if they do create a tiered access system.]]></description>
		<content:encoded><![CDATA[<p>Kevin, which plans to violate net neutrality are you talking about, cause I haven&#8217;t seen any? As far as I can tell, the telco&#8217;s aren&#8217;t going to do anything wrong, even if they do create a tiered access system.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.396 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-07 08:38:48 -->
