<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Spam update</title>
	<atom:link href="http://werblog.com/2006/12/spam-update-2/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2006/12/spam-update-2/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: Gen</title>
		<link>http://werblog.com/2006/12/spam-update-2/#comment-94</link>
		<dc:creator><![CDATA[Gen]]></dc:creator>
		<pubDate>Fri, 22 Dec 2006 08:15:39 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1395#comment-94</guid>
		<description><![CDATA[Kevin- please give us an update after whatever time you need to evaluate the service.]]></description>
		<content:encoded><![CDATA[<p>Kevin- please give us an update after whatever time you need to evaluate the service.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.392 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-07 10:40:51 -->
