<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: The Future of Microsoft</title>
	<atom:link href="http://werblog.com/2006/05/the-future-of-microsoft/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2006/05/the-future-of-microsoft/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: telephoneportablex</title>
		<link>http://werblog.com/2006/05/the-future-of-microsoft/#comment-87</link>
		<dc:creator><![CDATA[telephoneportablex]]></dc:creator>
		<pubDate>Sat, 23 Sep 2006 07:21:19 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1360#comment-87</guid>
		<description><![CDATA[can we know how much progress and in wich domains please]]></description>
		<content:encoded><![CDATA[<p>can we know how much progress and in wich domains please</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.416 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-04 22:22:42 -->
