<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: How games train tomorrow&#039;s business leaders</title>
	<atom:link href="http://werblog.com/2006/03/how-games-train-tomorrows-business-leaders/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2006/03/how-games-train-tomorrows-business-leaders/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: manjara</title>
		<link>http://werblog.com/2006/03/how-games-train-tomorrows-business-leaders/#comment-78</link>
		<dc:creator><![CDATA[manjara]]></dc:creator>
		<pubDate>Tue, 14 Mar 2006 08:49:36 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1320#comment-78</guid>
		<description><![CDATA[I thought I was alone in thinking that these MMOGs were applicable to business! I started looking at it back in &#039;97 with an account on Ultima and Starcraft later.
I think they can be used for more than training. Why aren&#039;t the user interfaces for a lot of management or &#039;real-time&#039; applications more like games?
I wonder what would be more productive for a CSR, a Starcraft-like interface or a Siebel interface....]]></description>
		<content:encoded><![CDATA[<p>I thought I was alone in thinking that these MMOGs were applicable to business! I started looking at it back in &#8217;97 with an account on Ultima and Starcraft later.<br />
I think they can be used for more than training. Why aren&#8217;t the user interfaces for a lot of management or &#8216;real-time&#8217; applications more like games?<br />
I wonder what would be more productive for a CSR, a Starcraft-like interface or a Siebel interface&#8230;.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.504 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-04 23:13:56 -->
