<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Twitter Updates for 2009-12-30</title>
	<atom:link href="http://werblog.com/2009/12/twitter-updates-for-2009-12-30/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2009/12/twitter-updates-for-2009-12-30/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
</channel>
</rss>

<!-- Dynamic page generated in 0.640 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-26 07:30:51 -->
