<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: The Potential for Wireless Breakthroughs</title>
	<atom:link href="http://werblog.com/2011/07/the-potential-for-wireless-breakthroughs/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2011/07/the-potential-for-wireless-breakthroughs/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
	<item>
		<title>By: semanticlp</title>
		<link>http://werblog.com/2011/07/the-potential-for-wireless-breakthroughs/#comment-549</link>
		<dc:creator><![CDATA[semanticlp]]></dc:creator>
		<pubDate>Wed, 23 Nov 2011 12:44:51 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/?p=2225#comment-549</guid>
		<description><![CDATA[Happy to learn it.]]></description>
		<content:encoded><![CDATA[<p>Happy to learn it.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Michael Gold</title>
		<link>http://werblog.com/2011/07/the-potential-for-wireless-breakthroughs/#comment-397</link>
		<dc:creator><![CDATA[Michael Gold]]></dc:creator>
		<pubDate>Fri, 29 Jul 2011 08:05:19 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/?p=2225#comment-397</guid>
		<description><![CDATA[I read the white paper and I didn&#039;t see that it supplies enough information to evaluate if this is new or mainly a reinvention or variant of multiuser MIMO. But he does provide enough information to call into question his claim that he can deliver only 2 ms latency, using that centralized signal processor. Plus, so far I also don&#039;t see any technical reason why the signal processing has to be so centralized. Could distribute major pieces of the job to the dot coms, seemed to me. Seems to be a business method.]]></description>
		<content:encoded><![CDATA[<p>I read the white paper and I didn&#8217;t see that it supplies enough information to evaluate if this is new or mainly a reinvention or variant of multiuser MIMO. But he does provide enough information to call into question his claim that he can deliver only 2 ms latency, using that centralized signal processor. Plus, so far I also don&#8217;t see any technical reason why the signal processing has to be so centralized. Could distribute major pieces of the job to the dot coms, seemed to me. Seems to be a business method.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.907 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-26 19:46:06 -->
