<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Twitter Updates for 2011-04-08</title>
	<atom:link href="http://werblog.com/2011/04/twitter-updates-for-2011-04-08/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2011/04/twitter-updates-for-2011-04-08/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: Pandora Australia</title>
		<link>http://werblog.com/2011/04/twitter-updates-for-2011-04-08/#comment-296</link>
		<dc:creator><![CDATA[Pandora Australia]]></dc:creator>
		<pubDate>Tue, 19 Apr 2011 02:41:56 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/2011/04/twitter-updates-for-2011-04-08/#comment-296</guid>
		<description><![CDATA[innovation as a social moveme]]></description>
		<content:encoded><![CDATA[<p>innovation as a social moveme</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.385 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-04 22:48:28 -->
