<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Getting Out of the Broadband Box</title>
	<atom:link href="http://werblog.com/2011/07/getting-out-of-the-broadband-box/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2011/07/getting-out-of-the-broadband-box/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: The Potential for Wireless Breakthroughs &#124; Werblog</title>
		<link>http://werblog.com/2011/07/getting-out-of-the-broadband-box/#comment-395</link>
		<dc:creator><![CDATA[The Potential for Wireless Breakthroughs &#124; Werblog]]></dc:creator>
		<pubDate>Thu, 28 Jul 2011 18:22:00 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/?p=2221#comment-395</guid>
		<description><![CDATA[[...] also need to look toward fundamental advances in the means of wireless communication.  As I said yesterday, experimentation is crucial for the future of the broadband [...]]]></description>
		<content:encoded><![CDATA[<p>[&#8230;] also need to look toward fundamental advances in the means of wireless communication.  As I said yesterday, experimentation is crucial for the future of the broadband [&#8230;]</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.477 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-04 21:49:53 -->
