<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Twitter Updates for 2011-04-11</title>
	<atom:link href="http://werblog.com/2011/04/twitter-updates-for-2011-04-11/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2011/04/twitter-updates-for-2011-04-11/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
	<item>
		<title>By: mindxstudio</title>
		<link>http://werblog.com/2011/04/twitter-updates-for-2011-04-11/#comment-547</link>
		<dc:creator><![CDATA[mindxstudio]]></dc:creator>
		<pubDate>Wed, 23 Nov 2011 12:40:47 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/2011/04/twitter-updates-for-2011-04-11/#comment-547</guid>
		<description><![CDATA[me too, can&#039;t able to get the required point. It&#039;s seems to me it is one day update from twitter.]]></description>
		<content:encoded><![CDATA[<p>me too, can&#8217;t able to get the required point. It&#8217;s seems to me it is one day update from twitter.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Sarah</title>
		<link>http://werblog.com/2011/04/twitter-updates-for-2011-04-11/#comment-496</link>
		<dc:creator><![CDATA[Sarah]]></dc:creator>
		<pubDate>Tue, 27 Sep 2011 19:39:59 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/2011/04/twitter-updates-for-2011-04-11/#comment-496</guid>
		<description><![CDATA[i cant understand what you want to say]]></description>
		<content:encoded><![CDATA[<p>i cant understand what you want to say</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Pandora</title>
		<link>http://werblog.com/2011/04/twitter-updates-for-2011-04-11/#comment-298</link>
		<dc:creator><![CDATA[Pandora]]></dc:creator>
		<pubDate>Tue, 19 Apr 2011 02:42:32 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/2011/04/twitter-updates-for-2011-04-11/#comment-298</guid>
		<description><![CDATA[Pages

    * About this Site]]></description>
		<content:encoded><![CDATA[<p>Pages</p>
<p>    * About this Site</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.404 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-25 13:11:53 -->
