<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: The Five Stages of Telecom Transition</title>
	<atom:link href="http://werblog.com/2011/12/telecom-transition/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2011/12/telecom-transition/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: FOREVERBLOG &#187; Daily Links 12/13/2011: Comcast in deal to distribute BBC</title>
		<link>http://werblog.com/2011/12/telecom-transition/#comment-585</link>
		<dc:creator><![CDATA[FOREVERBLOG &#187; Daily Links 12/13/2011: Comcast in deal to distribute BBC]]></dc:creator>
		<pubDate>Mon, 19 Dec 2011 01:10:49 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/?p=2316#comment-585</guid>
		<description><![CDATA[[...] The Five Stages of Telecom Transition (Werblog)By Wharton Prof and Telecom policy analyst Kevin Werbach. [...]]]></description>
		<content:encoded><![CDATA[<p>[&#8230;] The Five Stages of Telecom Transition (Werblog)By Wharton Prof and Telecom policy analyst Kevin Werbach. [&#8230;]</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.409 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-08 18:28:00 -->
