<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: E-A-G-L-E-S Eagles!!!</title>
	<atom:link href="http://werblog.com/2005/01/e-a-g-l-e-s-eagles/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/01/e-a-g-l-e-s-eagles/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: Chris Lehmann</title>
		<link>http://werblog.com/2005/01/e-a-g-l-e-s-eagles/#comment-9</link>
		<dc:creator><![CDATA[Chris Lehmann]]></dc:creator>
		<pubDate>Mon, 17 Jan 2005 22:29:07 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1157#comment-9</guid>
		<description><![CDATA[Kevin --

Super Bowl party uptown at our place. Come up for the shindig!]]></description>
		<content:encoded><![CDATA[<p>Kevin &#8212;</p>
<p>Super Bowl party uptown at our place. Come up for the shindig!</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.400 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-05 03:00:33 -->
