<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Kill the Competitors&#8230;, er, Parasites!</title>
	<atom:link href="http://werblog.com/2005/10/kill-the-competitors-er-parasites/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/10/kill-the-competitors-er-parasites/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: T-Bond</title>
		<link>http://werblog.com/2005/10/kill-the-competitors-er-parasites/#comment-71</link>
		<dc:creator><![CDATA[T-Bond]]></dc:creator>
		<pubDate>Wed, 26 Oct 2005 18:47:03 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1287#comment-71</guid>
		<description><![CDATA[I believe VZ and others are just making noise. They cannot afford to block traffic as their subscribers would move to other ISP&#039;s.

On the other hand, perhaps the reason Google is working on WIFI is to make sure the &quot;big boy content owners&quot; don&#039;t try a &quot;freeze out&quot;.

It seems that the major media has had such a lock for so long that they think they can dictate the market but the market is more powerful than they.]]></description>
		<content:encoded><![CDATA[<p>I believe VZ and others are just making noise. They cannot afford to block traffic as their subscribers would move to other ISP&#8217;s.</p>
<p>On the other hand, perhaps the reason Google is working on WIFI is to make sure the &#8220;big boy content owners&#8221; don&#8217;t try a &#8220;freeze out&#8221;.</p>
<p>It seems that the major media has had such a lock for so long that they think they can dictate the market but the market is more powerful than they.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.390 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-04 22:38:35 -->
