<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: A billion infomercials, all the time</title>
	<atom:link href="http://werblog.com/2005/01/a-billion-infomercials-all-the-time/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/01/a-billion-infomercials-all-the-time/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: Frank Ruscica</title>
		<link>http://werblog.com/2005/01/a-billion-infomercials-all-the-time/#comment-11</link>
		<dc:creator><![CDATA[Frank Ruscica]]></dc:creator>
		<pubDate>Sat, 29 Jan 2005 18:32:37 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1179#comment-11</guid>
		<description><![CDATA[Enter Land of OpportuniTV, a a startup comedy about making America the Silicon Valley of customized lifelong learning and career services, the global market that Peter Drucker says will be the biggest over the next 30 years

Details coming online at &lt;a href=&quot;http://www.opportunitv.com&quot; rel=&quot;nofollow&quot;&gt;&lt;a href=&quot;http://www.opportunitv.com&quot; rel=&quot;nofollow&quot;&gt;http://www.opportunitv.com&lt;/a&gt;&lt;/a&gt;]]></description>
		<content:encoded><![CDATA[<p>Enter Land of OpportuniTV, a a startup comedy about making America the Silicon Valley of customized lifelong learning and career services, the global market that Peter Drucker says will be the biggest over the next 30 years</p>
<p>Details coming online at <a href="http://www.opportunitv.com" rel="nofollow"></a><a href="http://www.opportunitv.com" rel="nofollow">http://www.opportunitv.com</a></p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.446 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-02 20:38:19 -->
