<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: &#034;It Just Works&#034;?</title>
	<atom:link href="http://werblog.com/2005/09/it-just-works/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/09/it-just-works/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: Kevin Werbach</title>
		<link>http://werblog.com/2005/09/it-just-works/#comment-60</link>
		<dc:creator><![CDATA[Kevin Werbach]]></dc:creator>
		<pubDate>Fri, 23 Sep 2005 01:08:57 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1249#comment-60</guid>
		<description><![CDATA[Gen, I&#039;ve taken it to the Genius Bar at the Apple Store, and they couldn&#039;t find anything that could be causing the problems.  They suggested I clone the hard drive and do a clean reinstall of OS X, which was the next thing I was going to try anyway.  I just haven&#039;t had time to go through that process yet.

The guy did tell me that installing third-party utilities can make OS X unstable, just like Windows.  I had been under the impression that Macs were less susceptible to that kind of problem, but evidently not.  I haven&#039;t put anything particularly unusual on the machine, and I still don&#039;t see how that can explain all the sporadic problems I&#039;ve had, but perhaps a clean reinstall will help.]]></description>
		<content:encoded><![CDATA[<p>Gen, I&#8217;ve taken it to the Genius Bar at the Apple Store, and they couldn&#8217;t find anything that could be causing the problems.  They suggested I clone the hard drive and do a clean reinstall of OS X, which was the next thing I was going to try anyway.  I just haven&#8217;t had time to go through that process yet.</p>
<p>The guy did tell me that installing third-party utilities can make OS X unstable, just like Windows.  I had been under the impression that Macs were less susceptible to that kind of problem, but evidently not.  I haven&#8217;t put anything particularly unusual on the machine, and I still don&#8217;t see how that can explain all the sporadic problems I&#8217;ve had, but perhaps a clean reinstall will help.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Gen</title>
		<link>http://werblog.com/2005/09/it-just-works/#comment-59</link>
		<dc:creator><![CDATA[Gen]]></dc:creator>
		<pubDate>Thu, 22 Sep 2005 01:48:42 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1249#comment-59</guid>
		<description><![CDATA[Kevin, have you sent your machine in for repairs or taken it to an Apple Store to have one of their techs look at it?  The list of problems you have is extensive.  I dont know of anyone  who has as many problems as you have.  We all have problems with our laptops, but I&#039;ve never seen so many in one machine.]]></description>
		<content:encoded><![CDATA[<p>Kevin, have you sent your machine in for repairs or taken it to an Apple Store to have one of their techs look at it?  The list of problems you have is extensive.  I dont know of anyone  who has as many problems as you have.  We all have problems with our laptops, but I&#8217;ve never seen so many in one machine.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.445 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-07 12:24:56 -->
