<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: The day of reckoning</title>
	<atom:link href="http://werblog.com/2005/03/the-day-of-reckoning/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/03/the-day-of-reckoning/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: A Rowland</title>
		<link>http://werblog.com/2005/03/the-day-of-reckoning/#comment-22</link>
		<dc:creator><![CDATA[A Rowland]]></dc:creator>
		<pubDate>Thu, 31 Mar 2005 19:24:28 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1217#comment-22</guid>
		<description><![CDATA[Kevin,  Totally agree on the importance of the Grokster case.  More attention was paid to the indecency issue, but this is where the real decision will be made about the future of (distributed) media and first amendment rights.  Without a positive ruling, cost of distribution for individuals will skyrockets and set the democracy in media movement back by a decade.]]></description>
		<content:encoded><![CDATA[<p>Kevin,  Totally agree on the importance of the Grokster case.  More attention was paid to the indecency issue, but this is where the real decision will be made about the future of (distributed) media and first amendment rights.  Without a positive ruling, cost of distribution for individuals will skyrockets and set the democracy in media movement back by a decade.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: smurfette</title>
		<link>http://werblog.com/2005/03/the-day-of-reckoning/#comment-21</link>
		<dc:creator><![CDATA[smurfette]]></dc:creator>
		<pubDate>Tue, 29 Mar 2005 17:21:29 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1217#comment-21</guid>
		<description><![CDATA[Come on, let&#039;s go to Washingotn, and I&#039;m thinking of going to law school!

But I think given the previous case of Sony vs. Disney&amp;Universal, those poor tech software guys should be fine. And personally I find it most ridiculous and nonsense trying to put ban on the innocent technology or programming. It is the people or system(still manipulated by human) that is flawed. And it would be really disastrous if the Court came to the conclusion against innovation and technologically developmental freedom.

On the other one about cable guy vs. telco guy, I have no idea who should get what or how is that justified, although fair and free competition has always been at the mouth of everybody.]]></description>
		<content:encoded><![CDATA[<p>Come on, let&#8217;s go to Washingotn, and I&#8217;m thinking of going to law school!</p>
<p>But I think given the previous case of Sony vs. Disney&#038;Universal, those poor tech software guys should be fine. And personally I find it most ridiculous and nonsense trying to put ban on the innocent technology or programming. It is the people or system(still manipulated by human) that is flawed. And it would be really disastrous if the Court came to the conclusion against innovation and technologically developmental freedom.</p>
<p>On the other one about cable guy vs. telco guy, I have no idea who should get what or how is that justified, although fair and free competition has always been at the mouth of everybody.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.384 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-02 20:15:45 -->
