<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Not the Internet</title>
	<atom:link href="http://werblog.com/2005/11/not-the-internet/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/11/not-the-internet/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: Rob Frieden</title>
		<link>http://werblog.com/2005/11/not-the-internet/#comment-74</link>
		<dc:creator><![CDATA[Rob Frieden]]></dc:creator>
		<pubDate>Fri, 04 Nov 2005 19:42:02 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1294#comment-74</guid>
		<description><![CDATA[Even assuming that Mr. Whiteacre was referring to IPTV, I still think he get&#039;s it wrong.  Content providers often self-provision, i.e., pay to bring content to a public peering point.  From that point isn&#039;t it fair to assume that subscribers&#039; broadband subscriptions entitle them to both upstream and downstream delivery of content?  If yes, doesn&#039;t this include the SBC portion upstream and downstream to the peering point, or even to the IPTV&#039;s on premises server?]]></description>
		<content:encoded><![CDATA[<p>Even assuming that Mr. Whiteacre was referring to IPTV, I still think he get&#8217;s it wrong.  Content providers often self-provision, i.e., pay to bring content to a public peering point.  From that point isn&#8217;t it fair to assume that subscribers&#8217; broadband subscriptions entitle them to both upstream and downstream delivery of content?  If yes, doesn&#8217;t this include the SBC portion upstream and downstream to the peering point, or even to the IPTV&#8217;s on premises server?</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.440 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-05 15:27:40 -->
