<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Shutting down a third of the Net</title>
	<atom:link href="http://werblog.com/2005/09/shutting-down-a-third-of-the-net/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/09/shutting-down-a-third-of-the-net/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.10</generator>
	<item>
		<title>By: manjara</title>
		<link>http://werblog.com/2005/09/shutting-down-a-third-of-the-net/#comment-67</link>
		<dc:creator><![CDATA[manjara]]></dc:creator>
		<pubDate>Fri, 30 Sep 2005 07:28:23 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1260#comment-67</guid>
		<description><![CDATA[I have a feeling that the net is quite &#039;resilient&#039;, and the usage is somewhat like water, eventually it will find another route.
If I was Steve Jobs I would be thinking up ways to disintermediate the record companies or rearrange their business model pretty radically.]]></description>
		<content:encoded><![CDATA[<p>I have a feeling that the net is quite &#8216;resilient&#8217;, and the usage is somewhat like water, eventually it will find another route.<br />
If I was Steve Jobs I would be thinking up ways to disintermediate the record companies or rearrange their business model pretty radically.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.645 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-06-22 03:09:15 -->
