<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: The backwards music business</title>
	<atom:link href="http://werblog.com/2005/02/the-backwards-music-business/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/02/the-backwards-music-business/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: julian.bond</title>
		<link>http://werblog.com/2005/02/the-backwards-music-business/#comment-15</link>
		<dc:creator><![CDATA[julian.bond]]></dc:creator>
		<pubDate>Mon, 28 Feb 2005 17:01:10 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1203#comment-15</guid>
		<description><![CDATA[Are they out of their tiny minds? What if halving the price for any song over 12 months old resulted in 10 or 100 times as many sales? What if cutting the price to $0.25 resulted in 1000 times the sales? Both of those scenarios are extremely plausible. Look at Big Champagne&#039;s stats for P2P downloads and the overall market is at least 1000 times bigger than iTMS.

My own belief (based on personal use of AllOfMp3) is that somewhere around $0.25 you stop thinking about the price at all, at all and simply down load as fast as you can think of things to search for.

I&#039;m not suggesting that first run music should be this price, but the labels have a vast back catalogue including many things that are simply unavailable on physical CD. They should be digitising every bit of audio they&#039;ve got as fast as possible and putting it all online at the above prices. Internet download sales are the first opportunity they&#039;ve had to really monetize this stuff. And right now it&#039;s just gathering dust. There&#039;s such a huge opportunity here, and all they seem to be able to see is their perceived need to protect sales of the next Nelly single. Short-termism at its worst.]]></description>
		<content:encoded><![CDATA[<p>Are they out of their tiny minds? What if halving the price for any song over 12 months old resulted in 10 or 100 times as many sales? What if cutting the price to $0.25 resulted in 1000 times the sales? Both of those scenarios are extremely plausible. Look at Big Champagne&#8217;s stats for P2P downloads and the overall market is at least 1000 times bigger than iTMS.</p>
<p>My own belief (based on personal use of AllOfMp3) is that somewhere around $0.25 you stop thinking about the price at all, at all and simply down load as fast as you can think of things to search for.</p>
<p>I&#8217;m not suggesting that first run music should be this price, but the labels have a vast back catalogue including many things that are simply unavailable on physical CD. They should be digitising every bit of audio they&#8217;ve got as fast as possible and putting it all online at the above prices. Internet download sales are the first opportunity they&#8217;ve had to really monetize this stuff. And right now it&#8217;s just gathering dust. There&#8217;s such a huge opportunity here, and all they seem to be able to see is their perceived need to protect sales of the next Nelly single. Short-termism at its worst.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.427 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-02 20:19:22 -->
