<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: The telco mindset</title>
	<atom:link href="http://werblog.com/2005/10/the-telco-mindset/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2005/10/the-telco-mindset/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.7</generator>
	<item>
		<title>By: Adam Peake</title>
		<link>http://werblog.com/2005/10/the-telco-mindset/#comment-72</link>
		<dc:creator><![CDATA[Adam Peake]]></dc:creator>
		<pubDate>Mon, 31 Oct 2005 09:42:31 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1289#comment-72</guid>
		<description><![CDATA[Interview&#039;s full of very up front stuff:

&quot;It&#039;s about owning the assets that connect customers. The assets that probably can&#039;t be duplicated except maybe by the cable companies&quot;  i.e. CLECs; squashed all that stuff, we&#039;re a monopoly and love it.

And on Telco TV (non) franchising &quot;The cable companies have an agreement with the cities: They pay a percentage of their revenue for a franchise right to broadcast TV. We have a franchise in every city we operate in based on providing telephone service ... If you want us to get a franchise agreement for TV, then let&#039;s make the cable companies get a franchise for telephony.&quot;]]></description>
		<content:encoded><![CDATA[<p>Interview&#8217;s full of very up front stuff:</p>
<p>&#8220;It&#8217;s about owning the assets that connect customers. The assets that probably can&#8217;t be duplicated except maybe by the cable companies&#8221;  i.e. CLECs; squashed all that stuff, we&#8217;re a monopoly and love it.</p>
<p>And on Telco TV (non) franchising &#8220;The cable companies have an agreement with the cities: They pay a percentage of their revenue for a franchise right to broadcast TV. We have a franchise in every city we operate in based on providing telephone service &#8230; If you want us to get a franchise agreement for TV, then let&#8217;s make the cable companies get a franchise for telephony.&#8221;</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.397 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-02-04 23:35:24 -->
