var quotes = new Array;
document.write(quotes[(Math.floor(Math.random() * quotes.length))]);
quotes.push("&quot;One of the must-attends of the digerati and forward thinkers of the networked age.&quot; -- John Seely Brown, Former Chief Scientist, Xerox");
quotes.push("&quot;As good as any conference anywhere.&quot; -- Lee Stein, CEO, Virtual Group");
quotes.push("&quot;The right folks, and the right forum, to advance the debate.&quot; -- Jonathan Schwartz, CEO, Sun Microsystems");
quotes.push("&quot;There are a lot of good conferences - Supernova is one of the best.&quot; -- John Patrick, Former VP, Internet Technology, IBM");
quotes.push("&quot;Superlative.&quot; -- Amy Wohl, Industry analyst");
quotes.push("&quot;What an awesome crowd.&quot; -- Rob Poor, CTO, Ember");
quotes.push("&quot;Without a doubt, one of the best technology / business conferences I have ever attended.&quot; -- Jack Devlin, Sr. Director, Fireman's Fund");
quotes.push("&quot;Great conference!&quot; -- Kim Polese, CEO, Spikesource");
quotes.push("&quot;Best networking I've ever had.  No question.  No debate.&quot; -- J. Scott Johnson, Founder, Feedster");
quotes.push("&quot;It was totally worthwhile. I'm addicted now.&quot; -- Joichi Ito, CEO, Neoteny");