<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Barack Obama and Technology Policy</title>
	<atom:link href="http://werblog.com/2007/03/barack-obama-and-technology-policy/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2007/03/barack-obama-and-technology-policy/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
	<item>
		<title>By: Gen</title>
		<link>http://werblog.com/2007/03/barack-obama-and-technology-policy/#comment-107</link>
		<dc:creator><![CDATA[Gen]]></dc:creator>
		<pubDate>Sat, 17 Mar 2007 01:39:00 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1450#comment-107</guid>
		<description><![CDATA[One of my friends who used to teach law at Seton Hall is now Obama&#039;s policy advisor.  It&#039;s still early to decide upon a candidate, but the field is looking interesting.]]></description>
		<content:encoded><![CDATA[<p>One of my friends who used to teach law at Seton Hall is now Obama&#8217;s policy advisor.  It&#8217;s still early to decide upon a candidate, but the field is looking interesting.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.395 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-25 21:35:17 -->
