<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Cringely&#039;s Take on Net Neutrality</title>
	<atom:link href="http://werblog.com/2007/04/cringelys-take-on-net-neutrality/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2007/04/cringelys-take-on-net-neutrality/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
	<item>
		<title>By: critic</title>
		<link>http://werblog.com/2007/04/cringelys-take-on-net-neutrality/#comment-111</link>
		<dc:creator><![CDATA[critic]]></dc:creator>
		<pubDate>Wed, 13 Jun 2007 19:48:51 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1471#comment-111</guid>
		<description><![CDATA[I haven&#039;t read the Cringley post yet, but I&#039;m curious if you think this inevitability of discrimination is global or US specific?

Personally, I&#039;m convinced you&#039;re probably correct with regard to the situation in the US. However, I have doubts whether it will be expropriated (sic) to the rest of the world.

Thoughts?]]></description>
		<content:encoded><![CDATA[<p>I haven&#8217;t read the Cringley post yet, but I&#8217;m curious if you think this inevitability of discrimination is global or US specific?</p>
<p>Personally, I&#8217;m convinced you&#8217;re probably correct with regard to the situation in the US. However, I have doubts whether it will be expropriated (sic) to the rest of the world.</p>
<p>Thoughts?</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: java</title>
		<link>http://werblog.com/2007/04/cringelys-take-on-net-neutrality/#comment-110</link>
		<dc:creator><![CDATA[java]]></dc:creator>
		<pubDate>Wed, 11 Apr 2007 16:31:58 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1471#comment-110</guid>
		<description><![CDATA[Cringley is correct, but I believe that the only ISPs that will remain will be those suppling the last mile to the consumer, who just happen to be the big propenents of a tiered Internet.  This is a partial result of AT&amp;T and Verizon eating their competition and therefore killing any intermodal competition.  Consumers will not pay AT&amp;T for DSL service then also pay AOL(not that I know what they could offer).  The broadband provider, as I see it, is the ISP.  The only competition that exists is between the different modes of communication: Cable, POTS, Sattellite, (WiFi when and if it becomes WiMAX).  The promise of ubiquitous wireless communication could change things, however, the point I have digressed from is that Robert Cringely is correct, but it begs the question who(or what) owns the Internet?]]></description>
		<content:encoded><![CDATA[<p>Cringley is correct, but I believe that the only ISPs that will remain will be those suppling the last mile to the consumer, who just happen to be the big propenents of a tiered Internet.  This is a partial result of AT&#038;T and Verizon eating their competition and therefore killing any intermodal competition.  Consumers will not pay AT&#038;T for DSL service then also pay AOL(not that I know what they could offer).  The broadband provider, as I see it, is the ISP.  The only competition that exists is between the different modes of communication: Cable, POTS, Sattellite, (WiFi when and if it becomes WiMAX).  The promise of ubiquitous wireless communication could change things, however, the point I have digressed from is that Robert Cringely is correct, but it begs the question who(or what) owns the Internet?</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.555 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-25 14:04:37 -->
