<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Small Whirrled</title>
	<atom:link href="http://werblog.com/2007/03/small-whirrled/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2007/03/small-whirrled/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
	<item>
		<title>By: Kevin Werbach</title>
		<link>http://werblog.com/2007/03/small-whirrled/#comment-109</link>
		<dc:creator><![CDATA[Kevin Werbach]]></dc:creator>
		<pubDate>Fri, 30 Mar 2007 12:41:04 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1464#comment-109</guid>
		<description><![CDATA[Long before.  Larry and Sergey left Stanford to form Google in 1998.  We started Whirrled in 1995, around the time Amazon.com and eBay were started, and not long after Yahoo.]]></description>
		<content:encoded><![CDATA[<p>Long before.  Larry and Sergey left Stanford to form Google in 1998.  We started Whirrled in 1995, around the time Amazon.com and eBay were started, and not long after Yahoo.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: adamwerbach</title>
		<link>http://werblog.com/2007/03/small-whirrled/#comment-108</link>
		<dc:creator><![CDATA[adamwerbach]]></dc:creator>
		<pubDate>Fri, 30 Mar 2007 12:16:55 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=1464#comment-108</guid>
		<description><![CDATA[I suppose that&#039;s the glorious nature of the archive of the web.  If I recall correctly, we began whirrled before google even existed.]]></description>
		<content:encoded><![CDATA[<p>I suppose that&#8217;s the glorious nature of the archive of the web.  If I recall correctly, we began whirrled before google even existed.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.574 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-26 16:46:51 -->
