<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Listening to Yogi on Interconnection and Net Neutrality</title>
	<atom:link href="http://werblog.com/2014/05/yogi/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2014/05/yogi/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
	<item>
		<title>By: antonejohnson</title>
		<link>http://werblog.com/2014/05/yogi/#comment-2957</link>
		<dc:creator><![CDATA[antonejohnson]]></dc:creator>
		<pubDate>Wed, 28 May 2014 14:53:06 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/?p=6570#comment-2957</guid>
		<description><![CDATA[Sec 706 is only #NetNeutrality #FCC jurisdiction approach that&#039;s been validated in court: http://t.co/5PuuM4zVBL via @kwerb @martingeddes]]></description>
		<content:encoded><![CDATA[<p>Sec 706 is only #NetNeutrality #FCC jurisdiction approach that&#8217;s been validated in court: <a href="http://t.co/5PuuM4zVBL" rel="nofollow">http://t.co/5PuuM4zVBL</a> via @kwerb @martingeddes</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Anonymous</title>
		<link>http://werblog.com/2014/05/yogi/#comment-2952</link>
		<dc:creator><![CDATA[Anonymous]]></dc:creator>
		<pubDate>Wed, 28 May 2014 14:26:21 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/?p=6570#comment-2952</guid>
		<description><![CDATA[partially competitive &#038; partially regulated a disaster? EVERY us industry from oil to food is thusly reg&#039;d!]]></description>
		<content:encoded><![CDATA[<p>partially competitive &amp; partially regulated a disaster? EVERY us industry from oil to food is thusly reg&#8217;d!</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.567 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-29 11:50:43 -->
