<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Twitter Updates for 2011-10-27</title>
	<atom:link href="http://werblog.com/2011/10/twitter-updates-for-2011-10-27/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2011/10/twitter-updates-for-2011-10-27/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
	<item>
		<title>By: mindxstudioblog</title>
		<link>http://werblog.com/2011/10/twitter-updates-for-2011-10-27/#comment-553</link>
		<dc:creator><![CDATA[mindxstudioblog]]></dc:creator>
		<pubDate>Wed, 23 Nov 2011 13:02:47 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/2011/10/twitter-updates-for-2011-10-27/#comment-553</guid>
		<description><![CDATA[Happy to read your twitter update.]]></description>
		<content:encoded><![CDATA[<p>Happy to read your twitter update.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.614 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-25 11:43:45 -->
