<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Twitter Updates for 2011-04-06</title>
	<atom:link href="http://werblog.com/2011/04/twitter-updates-for-2011-04-06/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2011/04/twitter-updates-for-2011-04-06/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
	<item>
		<title>By: semantictemplates</title>
		<link>http://werblog.com/2011/04/twitter-updates-for-2011-04-06/#comment-551</link>
		<dc:creator><![CDATA[semantictemplates]]></dc:creator>
		<pubDate>Wed, 23 Nov 2011 12:58:43 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/2011/04/twitter-updates-for-2011-04-06/#comment-551</guid>
		<description><![CDATA[it&#039;s a twitter update.]]></description>
		<content:encoded><![CDATA[<p>it&#8217;s a twitter update.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Pandora Australia</title>
		<link>http://werblog.com/2011/04/twitter-updates-for-2011-04-06/#comment-300</link>
		<dc:creator><![CDATA[Pandora Australia]]></dc:creator>
		<pubDate>Tue, 19 Apr 2011 02:43:10 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/2011/04/twitter-updates-for-2011-04-06/#comment-300</guid>
		<description><![CDATA[March 2011]]></description>
		<content:encoded><![CDATA[<p>March 2011</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.419 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-26 06:21:55 -->
