<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Twitter Updates for 2012-04-06</title>
	<atom:link href="http://werblog.com/2012/04/twitter-updates-for-2012-04-06/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2012/04/twitter-updates-for-2012-04-06/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
	<item>
		<title>By: Alisa</title>
		<link>http://werblog.com/2012/04/twitter-updates-for-2012-04-06/#comment-1025</link>
		<dc:creator><![CDATA[Alisa]]></dc:creator>
		<pubDate>Sat, 07 Apr 2012 04:59:32 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/2012/04/twitter-updates-for-2012-04-06/#comment-1025</guid>
		<description><![CDATA[Wall Street is unlikely to automate trading in opaque areas of the bond market over the next two to three years because large investors do not want to trade electronically, according to a report on Wednesday.]]></description>
		<content:encoded><![CDATA[<p>Wall Street is unlikely to automate trading in opaque areas of the bond market over the next two to three years because large investors do not want to trade electronically, according to a report on Wednesday.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.418 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-26 12:23:46 -->
