<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: My Article for The Conversation on Gamification</title>
	<atom:link href="http://werblog.com/2015/03/article-conversation-gamification/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2015/03/article-conversation-gamification/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
	<item>
		<title>By: Anonymous</title>
		<link>http://werblog.com/2015/03/article-conversation-gamification/#comment-27052</link>
		<dc:creator><![CDATA[Anonymous]]></dc:creator>
		<pubDate>Thu, 07 May 2015 08:16:57 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/?p=7564#comment-27052</guid>
		<description><![CDATA[The differences between a gamified system that incorporates good design principles and one that doesn’t aren’t always obvious on the surface...let&#039;s see why.]]></description>
		<content:encoded><![CDATA[<p>The differences between a gamified system that incorporates good design principles and one that doesn’t aren’t always obvious on the surface&#8230;let&#8217;s see why.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.399 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-25 00:46:04 -->
