<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Spam prevention is going to</title>
	<atom:link href="http://werblog.com/2002/06/spam-prevention-is-going-to/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2002/06/spam-prevention-is-going-to/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.8</generator>
	<item>
		<title>By: Travis Carter</title>
		<link>http://werblog.com/2002/06/spam-prevention-is-going-to/#comment-2</link>
		<dc:creator><![CDATA[Travis Carter]]></dc:creator>
		<pubDate>Thu, 06 Oct 2005 19:48:04 +0000</pubDate>
		<guid isPermaLink="false">http://werbach.com/wordpress/?p=70#comment-2</guid>
		<description><![CDATA[You were right.  Spam prevention is a growing market every day.]]></description>
		<content:encoded><![CDATA[<p>You were right.  Spam prevention is a growing market every day.</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.399 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-03-17 21:04:05 -->
