<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Twitter Updates for 2012-02-23</title>
	<atom:link href="http://werblog.com/2012/02/twitter-updates-for-2012-02-23/feed/" rel="self" type="application/rss+xml" />
	<link>http://werblog.com/2012/02/twitter-updates-for-2012-02-23/</link>
	<description>The World According to Kevin Werbach</description>
	<lastBuildDate>Sun, 14 Feb 2016 11:16:03 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.4.4</generator>
	<item>
		<title>By: supermalyhlj</title>
		<link>http://werblog.com/2012/02/twitter-updates-for-2012-02-23/#comment-621</link>
		<dc:creator><![CDATA[supermalyhlj]]></dc:creator>
		<pubDate>Fri, 24 Feb 2012 09:34:41 +0000</pubDate>
		<guid isPermaLink="false">http://werblog.com/2012/02/twitter-updates-for-2012-02-23/#comment-621</guid>
		<description><![CDATA[不错的 支持一下吧]]></description>
		<content:encoded><![CDATA[<p>不错的 支持一下吧</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.445 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2016-08-23 17:28:49 -->
