<table class="header" width="100%" cellpadding="2" cellspacing="0">
  <tr>
     <td>
  <a class="headerlink" href="logout.php?root=people">
     HOME / LOGOUT</a>
  <a class="headerlink" href="people_search_form.php">
       SEARCH/EDIT</a>
  <a class="headerlink" href="people_add_form.php">
          ADD</a>
  <a class="headerlink" href="people_import.php">
          IMPORT</a>
     </td>
  </tr>
</table>
<br>
